version: "3"
services:
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    ports:
      - "4000:4000"
    links:
      - db
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

volumes:
  db:
