FROM node:8.0

RUN apt-get update && \
    apt-get install -y \
      postgresql-client \
      vim
WORKDIR /usr/src/app

ARG NODE_ENV
ENV NODE_ENV $NODE_ENV
COPY api/package.json /usr/src/app
RUN npm install && npm cache clean --force
# COPY . /usr/src/app

CMD ["npm", "start"]
